### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by smolkaj** [arlencox/mlbdd#4]
First off, thanks for the fantastic library, @arlencox!
I was wondering, do you have any sense of how your library compares against C implementations (such as BuDDY or CUDD) in terms of performance?

**Comment by arlencox** [comment]
Hi Steffen, mlbdd performs quite poorly compared to cudd.  I have not compared it to buddy, but given that buddy and cudd are quite similar in terms of performance, I expect that mlbdd is poor compared to buddy.  Fundamentally, cudd manages memory better than mlbdd can.  This is critically important because BDDs are incredibly allocator intensive.  The actual representation used by mlbdd is the same as the one used by cudd (modulo reordering, which mlbdd does not do).

The one scenario where mlbdd performs better than cudd is when the index of variables is arbitrary integers.  This is because cudd allocates an array where the variable index is the index of the array.  This array is traversed during garbage collection and reordering operations, so if you you simply create a BDD with the variable 1 billion, cudd performs very poorly.  mlbdd does not have this limitation.

Please note that there is a wrapper around cudd for ocaml.  For native code applications the interface has a lot of similarity with mlbdd.  In fact, I swap them out regularly.  You can install cudd with

```
opam install mlcuddidl
```

Documentation for that library is here: http://pop-art.inrialpes.fr/~bjeannet/mlxxxidl-forge/mlcuddidl/index.html

There are a few reasons that I can think of for still using mlbdd as opposed to cudd:

1. Because mlbdd is ocaml only it is easier to get it running on a system than a mixed c/ocaml solution.
2. Because mlbdd is ocaml only it it can be used with bucklescript or with js_of_ocaml to make a javascript version of a program.
3. It does not suffer from the large index number problem.
4. It is easier to extend to support custom structures.

**Comment by smolkaj** [comment]
Thanks for the detailed answer! Can you give a rough estimate of how much slower mlbdd is compared to CUDD? Are we talking 10x/100x/1000x? A very crude approximation would already be helpful.

**Comment by arlencox** [comment]
I haven't measured in a while.  I think it's somewhere around 10x without reordering.  With reordering cudd can be exponentially faster.

**Comment by smolkaj** [comment]
Thanks!
